### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tollsimy** [tollsimy/Gianni-s_Inventory#1]
- [ ] Fix ordering by integer and not by string on integer columns
- [ ] add independency from database, need to fix table types and add product.
- [ ] Show all / hide buttons and select (all / none)
- [ ] Enlarge/shrink columns
